#!/bin/bash
# based on a function found in bashtstyle-ng 5.0b1
# Original author Christopher Roy Bratusek (http://www.nanolx.org)
# Last arranged by ayoli (http://ayozone.org) 2008-02-04 17:16:43 +0100 CET 


		export black="\[\033[0;38;5;0m\]"
		export red="\[\033[0;38;5;1m\]"
		export orange="\[\033[0;38;5;130m\]"
		export green="\[\033[0;38;5;2m\]"
		export yellow="\[\033[0;38;5;3m\]"
		export blue="\[\033[0;38;5;4m\]"
		export bblue="\[\033[0;38;5;12m\]"
		export magenta="\[\033[0;38;5;55m\]"
		export cyan="\[\033[0;38;5;6m\]"
		export white="\[\033[0;38;5;7m\]"
		export coldblue="\[\033[0;38;5;33m\]"
		export smoothblue="\[\033[0;38;5;111m\]"
		export iceblue="\[\033[0;38;5;45m\]"
		export turqoise="\[\033[0;38;5;50m\]"
		export smoothgreen="\[\033[0;38;5;42m\]"

		export grey="\[\033[38;5;239m\]"

		export grey1="\[\033[48;5;232m\]"
		export grey2="\[\033[48;5;233m\]"
		export grey3="\[\033[48;5;234m\]"
		export grey4="\[\033[48;5;235m\]"
		export grey5="\[\033[48;5;236m\]"
		export grey6="\[\033[48;5;237m\]"
		export grey7="\[\033[48;5;238m\]"
		export grey8="\[\033[48;5;239m\]"

 list_colors(){
colors="$black black \n$grey grey \n$red red \n$orange orange \n$green green \n$blue blue \n$bblue bblue \n$magenta magenta \n$cyan cyan \n$white white \n$coldblue coldblue \n$smoothblue smoothblue \n$iceblue iceblue \n$turqoise turqoise \n$smoothgreen smoothgreen" 
echo -e $colors | sed 's/\\\[//g' | sed 's/\\\]//g'

}
alias "lc"="list_colors"
source ~/.git-completion.sh
source ~/.git-prompt.sh
source ~/.git-flow-completion.bash

export VIRTUAL_ENV_DISABLE_PROMPT=1
add_venv_info () {
if [ "x" != x ] ; then
	VIRT_ENV_TXT=""
else
	if [ "`basename \"$VIRTUAL_ENV\"`" = "__" ] ; then
		# special case for Aspen magic directories
		# see http://www.zetadev.com/software/aspen/
		VIRT_ENV_TXT="[`basename \`dirname \"$VIRTUAL_ENV\"\``]"
		elif [ "$VIRTUAL_ENV" != "" ]; then
			VIRT_ENV_TXT="(`basename \"$VIRTUAL_ENV\"`)"
		fi
	fi
	if [ "${VIRT_ENV_TXT}" != "" ]; then
   		echo ${VIRT_ENV_TXT}" "
	fi
#fi
}

_ps1_clear() {
    echo -n "\e[0m"
}
#_parse_git_branch() {
    #if [[ `git status 2> /dev/null` == *nothing\ to\ commit* ]]; then _ps1_fg 99; else _ps1_fg 32; fi
    #git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
#}
if [ -z "$mini" ]; then
export mini='0'
fi
export pcolor=$orange
export GIT_PS1_SHOWCOLORHINTS=true
_update_ps1() {
if [ $mini == '1' ]; then
		#USER=$(whoami)
		DIR=$(pwd)
		dircolor=$white
		if ! [ -w $DIR ]; then 
			dircolor=$red
		fi
		usercolor=$grey
		if [ $USER == 'root' ]; then
			usercolor="\[\033[0;38;5;11m\]"
		fi
		local git=$(__git_ps1 \"git: %b\")
		if [ ! -z "$git" ]; then
		local parts="$usercolor$grey2 \u $coldblue$grey3 \H $dircolor$grey4 \w $grey6 \$(__git_ps1 \"git: %b\")$white$grey6 $white$grey4 \$ $white"
		else
		local parts="$usercolor$grey2 \u $coldblue$grey3 \H $dircolor$grey4 \w \$ $white"
		fi
    	export PS1="${parts[@]}"
else
export PS1="$bblue┌─$green\$(add_venv_info)\
$bblue($pcolor\u@\h \$(date \"+%a, %d %b %y\")$bblue)─($pcolor\w\
$bblue)─┐\n$bblue└─($pcolor\$(__git_ps1 \"(git: %b) \")\$(date \"+%H:%M\") \$$bblue)─>$white "
fi
}
export PROMPT_COMMAND="_update_ps1"


