#!/bin/bash


#==================
# history settings
#

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=800000
HISTFILESIZE=800000
HISTTIMEFORMAT="%Y-%m-%dT%H:%M:%S "


#====================
# window size
#

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize



#==================================
# color prompt and some git stuff
#

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

#if [ "$color_prompt" = yes ]; then
#	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (git: %s)")\$ '
#else
#	PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w$(__git_ps1 " (git: %s)")\$ '
#fi
#unset color_prompt force_color_prompt


#========================
# ls and grep aliases
#

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=always'
    alias grep='grep --color=always'
    alias fgrep='fgrep --color=always'
    alias egrep='egrep --color=always'
	alias less='less -Xr'
fi

# cpu scaling
alias low='sudo cpupower frequency-set -g powersave'
alias mid='sudo cpupower frequency-set -g ondemand'
alias high='sudo cpupower frequency-set -g performance'

# To check a process is running in a box with a heavy load: pss
alias pss='ps -Af | grep $1'

# usefull alias to browse your filesystem for heavy usage quickly
#alias ducks='ls -A | grep -v -e '\''^\.\.$'\'' |xargs -i du -ks {} |sort -rn |head -16 | awk '\''{print $2}'\'' | xargs -i du -hs {}'
alias ducks='du -h -d 1 | sort -h' 

# cool colors for manpages
alias man="TERMINFO=~/.terminfo TERM=mostlike LESS=C PAGER=less man"


# some more ls aliases
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'

# beloved dir color for light console
LS_COLORS=di=33:ex=32

#alias for apt
alias install='sudo apt-get install $1'
alias update='sudo apt-get update'
alias upgrade='update && sudo apt-get dist-upgrade'
alias remove='sudo apt-get remove $1'
alias search='apt-cache search $1'

#====================
# git and svn stuff

#====================
# Handy Extract Program
#
function extract()    # Handy Extract Program.
{
     if [ -f $1 ] ; then
         case $1 in
             *.tar.bz2)   tar xvjf $1     ;;
             *.tar.gz)    tar xvzf $1     ;;
             *.bz2)       bunzip2 $1      ;;
             *.rar)       unrar x $1      ;;
             *.gz)        gunzip $1       ;;
             *.tar)       tar xvf $1      ;;
             *.tbz2)      tar xvjf $1     ;;
             *.tgz)       tar xvzf $1     ;;
             *.zip)       unzip $1        ;;
             *.Z)         uncompress $1   ;;
             *.7z)        7z x $1         ;;
             *)           echo "'$1' cannot be extracted via >extract<" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

SVN_EDITOR=vim

#alias git-log='git log --pretty="format:%t | %ai %d    --- %cn"'
alias git-log="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1

source ~/.git-completion.sh
source ~/.git-prompt.sh
source ~/.git-flow-completion.bash
