#!/bin/bash
# based on a function found in bashtstyle-ng 5.0b1
# Original author Christopher Roy Bratusek (http://www.nanolx.org)
# Last arranged by ayoli (http://ayozone.org) 2008-02-04 17:16:43 +0100 CET 


		export black="\[\033[0;38;5;0m\]"
		export red="\[\033[0;38;5;1m\]"
		export orange="\[\033[0;38;5;130m\]"
		export green="\[\033[0;38;5;2m\]"
		export yellow="\[\033[0;38;5;3m\]"
		export blue="\[\033[0;38;5;4m\]"
		export bblue="\[\033[0;38;5;12m\]"
		export magenta="\[\033[0;38;5;55m\]"
		export cyan="\[\033[0;38;5;6m\]"
		export white="\[\033[0;38;5;7m\]"
		export coldblue="\[\033[0;38;5;33m\]"
		export smoothblue="\[\033[0;38;5;111m\]"
		export iceblue="\[\033[0;38;5;45m\]"
		export turqoise="\[\033[0;38;5;50m\]"
		export smoothgreen="\[\033[0;38;5;42m\]"

source ~/.git-completion.sh
source ~/.git-prompt.sh
source ~/.git-flow-completion.bash

export VIRTUAL_ENV_DISABLE_PROMPT=1

add_venv_info () {
if [ "x" != x ] ; then
	VIRT_ENV_TXT=""
else
	if [ "`basename \"$VIRTUAL_ENV\"`" = "__" ] ; then
		# special case for Aspen magic directories
		# see http://www.zetadev.com/software/aspen/
		VIRT_ENV_TXT="[`basename \`dirname \"$VIRTUAL_ENV\"\``]"
		elif [ "$VIRTUAL_ENV" != "" ]; then
			VIRT_ENV_TXT="(`basename \"$VIRTUAL_ENV\"`)"
		fi
	fi
	if [ "${VIRT_ENV_TXT}" != "" ]; then
   		echo ${VIRT_ENV_TXT}" "
	fi
#fi
}

pcolor=$orange

PS1="$bblue┌─$green\$(add_venv_info)\
$bblue($pcolor\u@\h \$(date \"+%a, %d %b %y\")$bblue)─($pcolor\w\
$bblue)─┐\n$bblue└─($pcolor\$(__git_ps1 \"(git: %s) \")\$(date \"+%H:%M\") \$$bblue)─>$white "


											##########################################################
											# enable programmable completion features (you don't need to enable
											# this, if it's already enabled in /etc/bash.bashrc).
#											if [ -f /etc/bash_completion ]; then
#													    . /etc/bash_completion
#												fi
											# CDPATH initialisation
#												CDPATH=.:~:/media/store:/media/sites
#												PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
